### ISSUE TITLE
Wrong \foreach while loading some libraries in tikz

### ISSUE THREAD

**Issue by cao-** [olsak/OpTeX#108]
When trying to load some libraries in Tikz, using the  `\usetikzlibrary` command, the macro `\foreach` has the OpTeX definition rather than that of Tikz.  Here is an example that fails:
```tex
\load[tikz]
\usetikzlibrary{graphs}
\bye
```
It doesn't fail if i redefine `\foreach`:
```tex
\load[tikz]\let\foreach=\_pgf_foreach
\usetikzlibrary{graphs}
\bye
```

I see that in tikz.opm we have `\addto \tikz@startup@env {\let\foreach=\pgffor@foreach}`:  maybe there is some other Tikz macro that we should modify in the same way.

**Comment by olsak** [comment]
Thank you for bug report. I tried to solve it by my last commit.

**Comment by cao-** [comment]
Thank you for solving it :)
