### ISSUE TITLE
wrong catcodes for unicode chars

### ISSUE THREAD

**Issue by Udi-Fogiel** [olsak/OpTeX#149]
With plain LuaTeX the following test returns true, while with OpTeX it returns false. 
```
\ifcat אa true\else false\fi
\bye
```  
Is this intentional?
I've noticed it when I tried to translate some of OpTeX's macro to hebrew, to ease the typing of a hebrew document.

**Comment by Udi-Fogiel** [comment]
Also happens with czech letters
```TeX
\the\catcode`\č % 12 with OpTeX, 11 with plain
\bye
```

**Comment by olsak** [comment]
Yes, it is intentional. Only classical plain TeX setting of catcodes 11 is provided.

I hope that if somebody wants to have letters from another language in control sequence names then he/she can set catcode 11 for such letters.

**Comment by Udi-Fogiel** [comment]
Ok, thanks for the quick response.
