### ISSUE TITLE
Different font for equation label (math font) and equation reference (text font)

### ISSUE THREAD

**Issue by cao-** [olsak/OpTeX#16]
`\_thednum` is defined as `(\_the\_dnum)`.  This way the label next to an equation gets displayed with the math font, instead the reference number in the text gets displayed with the text font. According to me this is strange.  I suggest to redefine it as `\hbox{(\_the\_dnum)}` for consistency.

On the same topic, the `\fnotenum` is printed in math mode.  The printing is defined as `\_def\_printfnotemark {$^{\_fnotenum}$}`.  I think it should be `\_def\_printfnotemark {$^\mathbox{\_fnotenum}$}`.

Obviously all these definitions can be changed by the user, like I did, but I think that having them by default would be more consistent.   What is your opinion?

**Comment by olsak** [comment]
My opinion is that there is my mistake in `\_thednum` definition/usage. Thank you for your report. I supposed that only digits are here and digits in text font are the same as in math mode. But you are right: my assumption is not true.
I don't know where is better place to correct this: in `\eqmark` macro body: replace `\_thednum` usage by `\_hbox{\_thednum}` or only in `\_thednum` definition.
The `\fnotenum` is correct, IMHO. Both: pointer to footnote and label before footnote are printed with the same font: mathfont in scriptsize.

**Comment by cao-** [comment]
Depending on the combination of text font and math font, digits may be different in text and math.
About `\footnote`, you are right, the pointer and the label are consistent, so it may just be a matter of personal preference (I'd prefer the text font over the math font) and can be leaved as is---the users may redefine it if they wish.
Regarding your doubt, probably it's better to correct it in `\eqmark`.  But I don't see much difference from the user point of view.  Anyhow, the choice is up to you, the author is you :)
