### ISSUE TITLE
Unexpected whitespace when using `\crx` / `\crtop` via autoload

### ISSUE THREAD

**Issue by robertbachmann** [olsak/OpTeX#165]
Example to reproduce:

```tex
\fontfam[lm]
%\loadtrick\crx \loadtrick\crtop

\frame{\table{ll}{\crx 
1&2\crx 
3&4 \crx
5&6
}}

\bigskip \bigskip

\frame{\table{ll}{\crtop
1&2\crmid
3&4 \cr
5&6\crbot
}}

\bye
```

Result:

![image](https://github.com/olsak/OpTeX/assets/599839/76c49e15-df4a-469b-80f5-9648ed98c887)

Note: If we uncomment line 2, everything works as expected.

**Comment by robertbachmann** [comment]
I think documenting this restriction should be good enough.

**Comment by Udi-Fogiel** [comment]
Maybe we can use `tex.runtoks`?

```tex
\fontfam[lm]

\def\crx{%
	\immediateassignment\_tmptoks={\_loadtrick\crx}%
	\directlua{tex.runtoks('_tmptoks',true)}\crx}
\def\crtop{%
	\immediateassignment\_tmptoks={\_loadtrick\crtop}%
	\directlua{tex.runtoks('_tmptoks')}\crtop}

%\edef\a{\crx}
%\meaning\a

%\meaning\crx

\frame{\table{ll}{\crx 
1&2\crx 
3&4 \crx
5&6
}}

\bigskip \bigskip

\frame{\table{ll}{\crtop
1&2\crmid
3&4 \cr
5&6\crbot
}}

%\meaning\crx

\bye
```

**Comment by Udi-Fogiel** [comment]
It is also possible to define a new "pseudoprimitive",  based on `tex.runtoks`, that will allow to create blocks of code that gets executed (not just expanded) during the expansion stage.  For example, here I define `\_beglocalcontrol`,  which starts the block (`\__endlocalcontrol` is already defined in LuaTeX ):

```TeX 
\fontfam[lm]

\_directlua{
define_lua_command("_beglocalcontrol", function()
	return tex.runtoks(token.get_next, true)
end)
}

\_def\_regtrick#1{\_ifx#1\_undefined
	\_def#1{\_beglocalcontrol\_loadtrick#1\_endlocalcontrol#1}%
	\_else\_badtrick\_fi}

\_let \crx \_undefined
\_let \crtop \_undefined

\_xargs \_regtrick \crx \crtop ;

\frame{\table{ll}{\crx 
1&2\crx 
3&4 \crx
5&6
}}

\bigskip \bigskip

\frame{\table{ll}{\crtop
1&2\crmid
3&4 \cr
5&6\crbot
}}

\bye
```

**Comment by olsak** [comment]
Thank you very much for noticing about `tex.runtoks`. I'll experiment with it and use it for autoloading optex tricks.

**Comment by olsak** [comment]
I hope that my last commit solves this issue. Thanks you very much Udi Fogiel.
