### ISSUE TITLE
Phantom bigger than real

### ISSUE THREAD

**Issue by cao-** [olsak/OpTeX#19]
```
\fontfam[lm]


$$\sqrt{\matrix{1 & 0 \cr 0 & 1}}$$

$$\sqrt{\phantom{\matrix{1 & 0 \cr 0 & 1}}}$$


\bye
```

The phantom expression has a bigger square root sign.  As I understand `\phantom`, the square root sign should have the same size with and without `\phantom`.

**Comment by cao-** [comment]
Probably the size of the phantom expression is that of
```
$$\sqrt{\displaystyle\matrix{1 & 0 \cr 0 & 1}}$$
```

**Comment by cao-** [comment]
Besides, in plain TeX the matrix in
```
$$\sqrt{\matrix{1 & 0 \cr 0 & 1}}$$
```
is in displaystyle, while in OpTeX isn't.  Is it intended?

**Comment by olsak** [comment]
Not, this was not intend. I didn't count rounding in \dimexp x/2. The intend is described at the bottom of page 23 in optex-math.pdf

**Comment by cao-** [comment]
Your commit fixed the problems, thank you!
