### ISSUE TITLE
Wrong size for math inside \mathbox

### ISSUE THREAD

**Issue by cao-** [olsak/OpTeX#24]
Ckeck this, please
```
\fontfam[lm]

\def\textA{\mathbox{letter $x$}}
\def\textB{\mathbox{letter } x}
\def\triple#1{{#1}^{{#1}^{#1}}}

$$
\triple\textA
$$

$$
\triple\textB
$$

\bye
```

You should see that in the first case the letter $x$ isn't correctly chosen in the script and scriptscript variants, but it is just a rescalement of the text variant.  If `\fontfam` is omitted, everything seems to work correctly.

**Comment by olsak** [comment]
I hope that the commit https://github.com/olsak/OpTeX/commit/77e8a05090a325b64c46fb0bc91804e2d9d1e189 solves this issue.

**Comment by cao-** [comment]
I tested it and it seems fine now.  Thank you.
