### ISSUE TITLE
Strange colour behaviour with slides

### ISSUE THREAD

**Issue by gromadan** [olsak/OpTeX#29]
Consider the following

    \slides
    \slideshow
    \Green A \Black B
    \pg;
    C \Green D
    \pg.

Now the letter C is green although I would expect black.

**Comment by olsak** [comment]
Fixed the bug with colors, thanks for reporting.
I added a piece of documentation about grouping when \slideshow is activated and I introduced new command \slideopen.

**Comment by vlasakm** [comment]
Should we revisit this, because of the new color system? What is expected, what works?

**Comment by olsak** [comment]
I hope that it is OK. Colors are respecting groups and we need not to do more.
