### ISSUE TITLE
Fraktur and caligraphic for alternative fonts

### ISSUE THREAD

**Issue by gromadan** [olsak/OpTeX#31]
Again, not really a bug, but a slight user unfriendliness: If you use a unicode font that does not contain caligraphic letters or fraktur, then the commands `\cal` and `\frak` stop working. I think that it would be better if the font files loaded some alternative in this case.

[You could argue that its the users choice to use a font family that does not contain these variants. Partially it is true, but on the other hand, in the definition of `\slides`, you are pushing the user to use Heros instead of LM. A naive user, who does not care, which fonts they are actually using, may be then a bit disappointed that `\cal` and `\frak` stopped working.]

**Comment by olsak** [comment]
I added XITSMath font loading when FiraMath is loaded in Heros. This is only first attempt to solution. I knw that FiraMath is very poor Math font: many standard math symbols are missing here. It will be needed to do more elaborate solution for this poor FiraMath font. Another solution is mentioned at OpteX trick 0030.
