### ISSUE TITLE
Add support for new hyphenation patterns

### ISSUE THREAD

**Issue by vlasakm** [olsak/OpTeX#36]
Yesterday `hyph-utf8` (source of all hyphenation patterns/exceptions OpTeX uses) package was updated (already in TeX Live pretest). It brought two new "languages":
 - Albanian,
 - Finnish (a "basic" variant named "school").

Some information can be found at https://tug.org/pipermail/tex-hyphen/2021-February/001853.html

This change would seem to be appropriate:

```diff
--- a/optex/base/hyphen-lan.opm
+++ b/optex/base/hyphen-lan.opm
@@ -208,6 +208,8 @@
 \_preplang sv    Swedish         sv                239 22
 \_preplang th    Thai            th                240 23
 \_preplang ethi  Ethiopic        mul-ethi          241 11
+\_preplang sq    Albanian        sq                242 22
+\_preplang fis   schoolFinnish   fi-x-school       243 11

    \_doc -----------------------------
    The \`\langlist` includes names of all languages which are ready to load
```

"ISO code" of school Finnish has to be decided (I put `fis` just as a possibility). 

Today seems to be the day of TeX Live [freeze](https://tug.org/texlive/) and there already has been a release of OpTeX for TeX Live. I don't know whether it is worth trying to squeeze this in.

PS: Albanian produces two warning (`warning  (hyphenation): a conflicting pattern has been ignored`) when processing `\patterns`. I have seen this before (Spanish I think) but can't reproduce it now. Either way this should be solved in the patterns directly. (Although it would be possible to temporarily set the undocumented `show_warning_message` callback.) And also the Finnish patterns are currently broken (missing `\patterns` command).

**Comment by olsak** [comment]
Thanks. 
... "I don't know whether it is worth trying to squeeze this in." 
I think it is not necessary. TeXlive is "live", no version is the "last". I'll add this when I'll see the hyph files in my TeXlive installation (tlmgr update --all does not install them yet).

**Comment by vlasakm** [comment]
Apparently both patterns are currently [broken](https://tug.org/pipermail/tex-live/2021-March/046632.html). No need to hurry then.

**Comment by vlasakm** [comment]
Closing this until there is progress in `hyph-utf8` as the situation hasn't changed since I started this issue.
