### ISSUE TITLE
Overbrace and underbrace does not work

### ISSUE THREAD

**Issue by legendre6891** [olsak/OpTeX#6]
Dear Petr,

First, thanks a lot for this fantastic package! The document (snippet taken from the manual)
```
  $\overbrace {b\cdot b\cdot b \cdots b}^{k\times}$
  \bye
```
produces the error

```
This is LuaTeX, Version 1.12.0 (TeX Live 2020)
 restricted system commands enabled.
(./test.tex This is OpTeX (Olsak's Plain TeX), version <Beta 0.15 Jun 2020>
! Undefined control sequence.
\overbrace ...align {\_kern .3em} \_downbracefill
                                                  \_crcr \_noalign {\_kern ....

l.1 $\overbrace {b\cdot b\cdot b \cdots b}
                                        ^{k\times}$
```

Any help would be appreciated, thanks!

**Comment by cao-** [comment]
It seems like there are missing private versions of two control sequences.  In the meantime you could solve it by
`
\private \downbracefill \upbracefill ;
 $\overbrace {b\cdot b\cdot b \cdots b}^{k\times}$
  \bye
`
The problem arises only if you don't load a font family.  When you do actually load a unicode font family, then the two missing control sequences get defined.

**Comment by legendre6891** [comment]
Thanks for that, @cao-.  To be more precise, the problem occurs when I don't load opentype math (i.e., I had a `\noloadmath` before `\fontfam[lmfonts]`). The reason is that I don't like the some of differences Latin Modern math brings (i.e., using `$\sum_{xxx}^{yyy}$` in inline math, the sub and superscripts are not positioned well).

Your workaround works very nicely!

**Comment by olsak** [comment]
Thank you for this report. The 7bit math (non-Unicode) was less tested by me. I'll commit a correction. You can write \private\downbracefill; in your document in order to solve this problem before the corrected version will be available.
