### ISSUE TITLE
Move `f-<fontfam>` files to their own directory

### ISSUE THREAD

**Issue by vlasakm** [olsak/OpTeX#70]
I know that the font family files are part of the "base", but maybe they would deserve a separate directory. There are alot of them and they are not really preloaded, but loaded on demand at runtime.

Not sure about the name, though. `families` or `fontfamilies` or `fonts` like in `csplain`? Should `fams-ini.opm` be moved too, as its just the index of them?

EDIT: Maybe the same thing for `hisyntax`?

**Comment by olsak** [comment]
All mentioned files are in the TEXINPUT pool. I don't see advantages. The tree needn't to be more complicated, IMHO.

**Comment by vlasakm** [comment]
I also forgot `bib-X` files.

My motivation:

 - There are a lot of files in `base` to scroll through. Most are font files.
 - `hisyntax-X`, `bib-X` and `f-X` files are not strictly part of the format, they are loaded at run time and follow certain namning conventions. They are distinct, because users can create their own variants with same names without modifying the format itself.
 - There will be possibly more of these font / hisyntax / bib files.

Everything under `$TEXMF/tex/optex` is in TEXINPUT, so there also aren't any disadvantages.

**Comment by olsak** [comment]
I dislike too bushy trees. My current directory includes testing files for OpTeX and single symlink to the `base/` of OpTeX which is named `base`. I am doing (with Tab completion, of course):
```
joe base/f-lmfonts.opm
joe base/fonts-select.opm
joe base/optex.ini
grep something base/*
etc.
```
My work will be more complicated if there is more than single point where all TEXINPUT files for OpTeX are. This is disadvantage from my point of view.

**Comment by vlasakm** [comment]
OK, maybe a comprise with `optex/base/hisyntax`, etc. could be made. Otherwise feel free to close the issue, it was just an idea.
