### ISSUE TITLE
Make OpTeX compatible with minim

### ISSUE THREAD

**Issue by vlasakm** [olsak/OpTeX#76]
[minim](https://www.ctan.org/pkg/minim) is a recent LuaTeX format. It can be used on its own, but it is modular and parts of it can be used in other formats. Maybe even OpTeX (users) could benefit from it. In particular it has:

 - mplib (metapost) support,
 - PDF tagging / XML metadata
 - different (in my opinion supreme) approach to Unicode mathematics

All these are nice and I would have maybe sometimes tried to tacke them myself. Now there wouldn't be any need to, and we could get them for "free".

Making OpTeX and minim usable together will require changes in both, since both depend on their own ways of handling allocations (minim-alloc.{tex,lua} vs alloc.opm + optex.lua) and callbacks (minim-callbacks.lua vs optex.lua). 

What do you think @olsak?

**Comment by olsak** [comment]
It would be nice to have a package `mp.opm` for metapost support, for example. We can inspire from the minim code. Or other similar packages inspired fro minim. But I don't plan to fundamentally change the OpTeX kernel in the minim sense.

**Comment by vlasakm** [comment]
Closed by https://github.com/olsak/OpTeX/commit/d0c577aabc2aca528574993b5f1018078c98a8c0
