### ISSUE TITLE
Curly braces not working with unicode fonts

### ISSUE THREAD

**Issue by gromadan** [olsak/OpTeX#81]
Ok, so as I now updated optex, something strange started to happen

    \fontfam[LMfonts]
    $\{a\}$
    \bye

Letters f and g are printed instead of the braces { and }.

**Comment by vlasakm** [comment]
I can't reproduce this with

```
This is LuaTeX, Version 1.13.2 (mmtex 20210902)
This is OpTeX (Olsak's Plain TeX), version <1.04 Aug.2021>
```

Can you share your log file for this input?

```
\fontfam[LMfonts]
$\{a\} \showlists$
\bye
```
