### ISSUE TITLE
Problem with \code and optex-tricks.html#inttinoval

### ISSUE THREAD

**Issue by robertbachmann** [olsak/OpTeX#99]
Using the following TeX adapted from http://petr.olsak.net/optex/optex-tricks.html#inttinoval

```tex
% !TeX program = optex
\fontfam[lm]

\def\_printinverbatim#1{%
	\leavevmode\global\setbox1000=\hbox{#1}%
     \inoval{\ht0=1.35ex \dp0=.15ex \box1000}}
\verbchar`

`C:\bootmgr` vs \code{C:\\bootmgr} 

\bye
```
I get this result: 

![image](https://user-images.githubusercontent.com/599839/170103698-ef6366c0-4206-4afa-944f-b8520fb7df98.png)

I tried to debug the issue myself, it seems to be related to `\_escapechar` in `\code<SPACE>` 
Using this adaptation I get the expected result (both "C:\bootmgr" in Ovals) _however_ I'm not
sure if my solution is 100% correct.

```tex
\_protected\_sdef{_code }#1{{\_escapechar=-1 \_ttfont \_the\_everyintt \_relax
\_edef\_tmpc{\_detokenize{#1}}\_escapechar=92
\_printinverbatim{\_tmpc}
}}
```

**Comment by olsak** [comment]
It seems that there was a bug in \optdef definition (\optdef'ed macros were dependent on \ecsapechar). I tried to fix this in my last commit.

**Comment by robertbachmann** [comment]
works now. Thanks!
